name: build-and-publish
on:
  schedule:
    - cron: "7 5 * * *"
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node generate.mjs || true
      - run: node scripts/build-sitemap.mjs || true
      - name: Commit docs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs || true
          git commit -m "publish: update docs" || echo "no changes"
          git push
